import { useEffect, useState } from "react";
import { Eye, Filter, RefreshCw, Search, Stethoscope } from "lucide-react";
import { Link } from "react-router-dom";
import MainSidebar from "../mainSidebar";
import { medicalVisitApi, unwrapList } from "../../../services/medicalVisitApi";

const badge = { VERIFIED:"bg-emerald-100 text-emerald-700", REJECTED:"bg-red-100 text-red-700", PENDING_VERIFICATION:"bg-amber-100 text-amber-800" };
export default function MedicalVisitReview() {
  const [visits, setVisits] = useState([]); const [status, setStatus] = useState("PENDING_VERIFICATION"); const [search, setSearch] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = async () => { setLoading(true); setError(""); try { setVisits(unwrapList(await medicalVisitApi.getVisits({status, search}))); } catch(err){setError(err.message);} finally{setLoading(false);} };
  // Reload when the selected status changes; searches run only when submitted.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { load(); }, [status]);
  const submitSearch = (e) => { e.preventDefault(); load(); };
  return <div className="min-h-screen bg-slate-100"><MainSidebar/><main className="ml-64 p-6 lg:p-8"><div className="mx-auto max-w-7xl"><div className="mb-7 flex items-center justify-between"><div><h1 className="flex items-center gap-2 text-2xl font-bold"><Stethoscope className="text-blue-700"/>Medical visits</h1><p className="text-slate-600">Review hospital submissions before they affect attendance.</p></div><button onClick={load} className="rounded-lg border bg-white p-2.5"><RefreshCw size={18}/></button></div>
  <div className="mb-5 flex flex-col gap-3 rounded-xl bg-white p-4 shadow-sm md:flex-row"><form onSubmit={submitSearch} className="flex flex-1"><div className="relative flex-1"><Search className="absolute left-3 top-2.5 text-slate-400" size={18}/><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Employee, tag or reference" className="w-full rounded-l-lg border py-2 pl-10 pr-3"/></div><button className="rounded-r-lg bg-blue-700 px-4 text-white">Search</button></form><div className="flex items-center gap-2"><Filter size={18}/><select value={status} onChange={(e)=>setStatus(e.target.value)} className="rounded-lg border px-3 py-2"><option value="">All statuses</option><option value="PENDING_VERIFICATION">Pending review</option><option value="VERIFIED">Verified</option><option value="REJECTED">Rejected</option></select></div></div>
  {error && <div className="mb-5 rounded-lg bg-red-50 p-4 text-red-700">{error}</div>}<section className="overflow-x-auto rounded-xl bg-white shadow-sm"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-slate-600"><tr><th className="p-4">Employee</th><th className="p-4">Hospital</th><th className="p-4">Visit date</th><th className="p-4">Excuse duty</th><th className="p-4">Status</th><th className="p-4"></th></tr></thead><tbody className="divide-y">{loading ? <tr><td colSpan="6" className="p-8 text-center text-slate-500">Loading…</td></tr> : visits.length===0 ? <tr><td colSpan="6" className="p-8 text-center text-slate-500">No medical visits found.</td></tr> : visits.map(v=><tr key={v.id} className="hover:bg-slate-50"><td className="p-4"><p className="font-medium">{v.employee?.displayName || v.employeeName}</p><p className="text-xs text-slate-500">{v.employee?.tagNumber || v.tagNumber}</p></td><td className="p-4">{v.hospital?.name || v.hospitalName}</td><td className="p-4">{v.visitDate}</td><td className="p-4">{v.requiresExcuseDuty ? `${v.excuseStartDate} – ${v.excuseEndDate}` : "Not requested"}</td><td className="p-4"><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${badge[v.status] || "bg-slate-100"}`}>{(v.status||"").replaceAll("_"," ")}</span></td><td className="p-4"><Link to={`/medical-visits/${v.id}`} className="inline-flex items-center gap-1 text-blue-700"><Eye size={16}/>Review</Link></td></tr>)}</tbody></table></section></div></main></div>;
}
