import { useEffect, useState } from "react";
import { ArrowLeft, CheckCircle2, FileText, XCircle } from "lucide-react";
import { Link, useNavigate, useParams } from "react-router-dom";
import MainSidebar from "../mainSidebar";
import { medicalVisitApi } from "../../../services/medicalVisitApi";
import PropTypes from "prop-types";

const Row = ({ label, value }) => <div><dt className="text-xs font-medium uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 text-slate-900">{value || "—"}</dd></div>;
Row.propTypes = { label: PropTypes.string.isRequired, value: PropTypes.node };
export default function MedicalVisitDetails() {
  const { id } = useParams(); const navigate = useNavigate(); const [visit,setVisit]=useState(null); const [comment,setComment]=useState(""); const [paid,setPaid]=useState(true); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  useEffect(()=>{medicalVisitApi.getVisit(id).then(setVisit).catch(e=>setError(e.message));},[id]);
  const decide=async(action)=>{if(action==="reject"&&!comment.trim()) return setError("Enter a rejection reason."); setBusy(true);setError("");try{if(action==="verify") await medicalVisitApi.verifyVisit(id,{hrComment:comment,paidExcuseDuty:paid});else await medicalVisitApi.rejectVisit(id,{hrComment:comment});navigate("/medical-visits");}catch(e){setError(e.message);}finally{setBusy(false);}};
  return <div className="min-h-screen bg-slate-100"><MainSidebar/><main className="ml-64 p-6 lg:p-8"><div className="mx-auto max-w-5xl"><Link to="/medical-visits" className="mb-5 inline-flex items-center gap-2 text-blue-700"><ArrowLeft size={18}/>Back to medical visits</Link>{error&&<div className="mb-5 rounded-lg bg-red-50 p-4 text-red-700">{error}</div>}{!visit?<div className="rounded-xl bg-white p-8 text-center">Loading…</div>:<><div className="mb-5 flex items-start justify-between rounded-xl bg-white p-6 shadow-sm"><div><p className="text-sm text-slate-500">Medical visit #{visit.referenceNumber||visit.id}</p><h1 className="mt-1 text-2xl font-bold">{visit.employee?.displayName||visit.employeeName}</h1><p className="text-slate-600">{visit.employee?.tagNumber||visit.tagNumber}</p></div><span className="rounded-full bg-amber-100 px-3 py-1 text-sm font-medium text-amber-800">{(visit.status||"").replaceAll("_"," ")}</span></div>
  <div className="grid gap-5 lg:grid-cols-2"><section className="rounded-xl bg-white p-6 shadow-sm"><h2 className="mb-5 font-semibold">Visit details</h2><dl className="grid gap-5 sm:grid-cols-2"><Row label="Hospital" value={visit.hospital?.name||visit.hospitalName}/><Row label="Visit date" value={visit.visitDate}/><Row label="Visit type" value={visit.visitType}/><Row label="Arrival / discharge" value={[visit.arrivalTime,visit.dischargeTime].filter(Boolean).join(" – ")}/><Row label="Hospital reference" value={visit.hospitalReference}/><Row label="Follow-up" value={visit.followUpDate}/><Row label="Submitted by" value={visit.submittedByName}/><Row label="Contact" value={visit.submittedByContact}/><div className="sm:col-span-2"><Row label="Remarks" value={visit.remarks}/></div></dl>{visit.attachmentUrl&&<a href={visit.attachmentUrl} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 text-blue-700"><FileText size={18}/>Open supporting document</a>}</section>
  <section className="rounded-xl bg-white p-6 shadow-sm"><h2 className="mb-5 font-semibold">Excuse-duty decision</h2><dl className="mb-6 grid gap-5 sm:grid-cols-2"><Row label="Requested" value={visit.requiresExcuseDuty?"Yes":"No"}/><Row label="Fit to return" value={visit.fitToReturn?"Yes":"No"}/><Row label="Start date" value={visit.excuseStartDate}/><Row label="End date" value={visit.excuseEndDate}/></dl><label className="mb-4 flex items-center gap-3 rounded-lg bg-slate-50 p-3"><input type="checkbox" checked={paid} onChange={e=>setPaid(e.target.checked)}/>Treat verified excuse duty as paid</label><label className="text-sm font-medium">HR comment<textarea rows="4" value={comment} onChange={e=>setComment(e.target.value)} className="mt-1 w-full rounded-lg border p-3" placeholder="Verification note or rejection reason"/></label>{visit.status === "PENDING_VERIFICATION"&&<div className="mt-5 grid grid-cols-2 gap-3"><button disabled={busy} onClick={()=>decide("reject")} className="flex items-center justify-center gap-2 rounded-lg border border-red-200 py-2.5 font-medium text-red-700"><XCircle size={18}/>Reject</button><button disabled={busy} onClick={()=>decide("verify")} className="flex items-center justify-center gap-2 rounded-lg bg-emerald-600 py-2.5 font-medium text-white"><CheckCircle2 size={18}/>Verify</button></div>}</section></div></>}</div></main></div>;
}
